export namespace Common {
  // These are the errors generated by Strummer validation.
  interface ValidationError {
    path: string;
    value: any;
    message: string;
  }

  export type NoContent = "";

  export interface OkResponse<T> {
    status: 200;
    message: null;
    result: T;
  }

  export interface BadRequestResponse {
    status: 400;
    message: string;
    errors: ValidationError[];
  }
}
